{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeFamilies #-}

-- generated by 'Morpheus' CLI
module Simple
  ( rootResolver
  )
where

import           Data.Typeable                  ( Typeable )
import           GHC.Generics                   ( Generic )
import           Data.Morpheus.Kind             ( SCALAR
                                                , ENUM
                                                , INPUT_OBJECT
                                                , OBJECT
                                                , UNION
                                                )
import           Data.Morpheus.Types            ( GQLRootResolver(..)
                                                , Resolver(..)
                                                , IORes
                                                , IOMutRes
                                                , IOSubRes
                                                , Event(..)
                                                , GQLType(..)
                                                , GQLScalar(..)
                                                , ScalarValue(..)
                                                , Undefined(..)
                                                , ResolveQ
                                                )
import           Data.Text                      ( Text )

rootResolver :: GQLRootResolver IO () Query Undefined Undefined
rootResolver = GQLRootResolver { queryResolver        = resolveQuery
                               , mutationResolver     = Undefined
                               , subscriptionResolver = Undefined
                               }

---- GQL Query ------------------------------- 
data Query m = Query
    { deity :: ArgDeity -> m (Deity m)
  ,  character :: ArgCharacter -> m (Character m)
    }
 deriving (Generic)

newtype ArgDeity = ArgDeity
    { name :: Maybe [Maybe [Maybe [[Maybe [Text]]]]]
    }
 deriving (Generic)

data ArgCharacter = ArgCharacter
    { characterID :: Text
  ,  age :: Maybe Int
    }
 deriving (Generic)

instance (Typeable m) => GQLType (Query m) where
  type KIND (Query m) = OBJECT

resolveQuery :: Query (IORes ())
resolveQuery =
  Query { deity = const resolveDeity, character = const resolveCharacter }

---- GQL Deity ------------------------------- 
data Deity m = Deity
    { fullName :: () -> m Text
  ,  power :: () -> m (Maybe Power)
    }
 deriving (Generic)

instance (Typeable m) => GQLType (Deity m) where
  type KIND (Deity m) = OBJECT

resolveDeity :: ResolveQ () IO Deity
resolveDeity =
  return Deity { fullName = const $ return "", power = const $ return Nothing }

---- GQL City ------------------------------- 
data City =
  Athens
  | Ithaca
  | Sparta
  | Troy deriving (Generic)

instance GQLType City where
  type KIND City = ENUM

resolveCity :: IORes () City
resolveCity = return Athens

---- GQL Power ------------------------------- 
data Power = Power Int Int

instance GQLType Power where
  type KIND Power = SCALAR

instance GQLScalar  Power where
  parseValue _ = pure (Power 0 0)
  serialize (Power x y) = Int (x + y)

resolvePower :: IORes () Power
resolvePower = return $ Power 0 0

---- GQL Creature ------------------------------- 
data Creature m = Creature
    { creatureName :: () -> m Text
  ,  realm :: () -> m City
  ,  immortality :: () -> m Bool
    }
 deriving (Generic)

instance Typeable m => GQLType (Creature m) where
  type KIND (Creature m) = OBJECT

resolveCreature :: ResolveQ () IO Creature
resolveCreature = return Creature { creatureName = const $ return ""
                                  , realm        = const resolveCity
                                  , immortality  = const $ pure False
                                  }

---- GQL Character ------------------------------- 
data Character m =
  Character_CREATURE (Creature m)
  | Character_DEITY (Deity m) deriving (Generic)

instance (Typeable m) => GQLType (Character m) where
  type KIND (Character m) = UNION

resolveCharacter :: ResolveQ () IO Character
resolveCharacter = Character_CREATURE <$> resolveCreature
