{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE DeriveAnyClass #-}


-- generated by 'Morpheus' CLI
module Simple
  ( rootResolver
  )
where

import           GHC.Generics                   ( Generic )
import           Data.Morpheus.Kind             ( SCALAR
                                                , ENUM
                                                , INPUT_OBJECT
                                                , OBJECT
                                                , UNION
                                                )
import           Data.Morpheus.Types            ( GQLRootResolver(..)
                                                , IORes
                                                , IOMutRes
                                                , IOSubRes
                                                , Event(..)
                                                , GQLType(..)
                                                , GQLScalar(..)
                                                , ScalarValue(..)
                                                , Undefined(..)
                                                , ResolveQ
                                                )
import           Data.Text                      ( Text )

rootResolver :: GQLRootResolver IO () Query Undefined Undefined
rootResolver = GQLRootResolver { queryResolver        = resolveQuery
                               , mutationResolver     = Undefined
                               , subscriptionResolver = Undefined
                               }


type ApiEvent = ()

---- GQL Query ------------------------------- 
data Query (m :: * -> *) = Query
    {   deity :: ArgDeity -> m (Deity m)
      ,  character :: ArgCharacter -> m (Character m)
    }
 deriving (Generic, GQLType)

newtype ArgDeity = ArgDeity
    { name :: Maybe [Maybe [Maybe [[Maybe [Text]]]]]
    }
 deriving (Generic)

data ArgCharacter = ArgCharacter
    { characterID :: Text
  ,  age :: Maybe Int
    }
 deriving (Generic)

resolveQuery :: Query (IORes ApiEvent)
resolveQuery =
  Query { deity = const resolveDeity, character = const resolveCharacter }

---- GQL Deity ------------------------------- 
data Deity (m :: * -> *) = Deity
    { fullName :: () -> m Text
  ,  power :: () -> m (Maybe Power)
    }
 deriving (Generic, GQLType)

resolveDeity :: ResolveQ ApiEvent IO Deity
resolveDeity =
  return Deity { fullName = const $ return "", power = const $ return Nothing }


---- GQL City ------------------------------- 
data City =
  Athens
  | Ithaca
  | Sparta
  | Troy deriving (Generic)

instance GQLType City where
  type KIND City = ENUM

resolveCity :: IORes ApiEvent City
resolveCity = return Athens

---- GQL Power ------------------------------- 
data Power = Power Int Int

instance GQLType Power where
  type KIND Power = SCALAR

instance GQLScalar  Power where
  parseValue _ = pure (Power 0 0)
  serialize (Power x y) = Int (x + y)

resolvePower :: IORes ApiEvent Power
resolvePower = return $ Power 0 0

---- GQL Creature ------------------------------- 
data Creature (m :: * -> *) = Creature
    { creatureName :: () -> m Text
  ,  realm :: () -> m City
  ,  immortality :: () -> m Bool
    }
 deriving (Generic, GQLType)

resolveCreature :: ResolveQ ApiEvent IO Creature
resolveCreature = return Creature { creatureName = const $ pure ""
                                  , realm        = const resolveCity
                                  , immortality  = const $ pure False
                                  }

---- GQL Character ------------------------------- 
data Character (m :: * -> *) =
  CharacterCreature (Creature m)
  | CharacterDeity (Deity m) deriving (Generic,GQLType)

resolveCharacter :: ResolveQ ApiEvent IO Character
resolveCharacter = CharacterCreature <$> resolveCreature
