name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        plan:
          - { lts: "-11.10" } # ghc-8.2.2
          - { lts: "-12.16" } # ghc-8.4.4
          - { lts: "" }
    runs-on: ubuntu-latest
    steps:
      - name: Prepare OS
        uses: mstksg/get-package@v1
        with:
          apt-get: ${{ matrix.apt-get }}
      - uses: actions/checkout@v1

      - name: Setup stack
        uses: nalchevanidze/setup-stack@v2.3

      - name: Install dependencies
        run: |
          stack build --fast --skip-ghc-check --no-terminal --test --only-dependencies
        env:
          STACK_YAML: stack${{ matrix.plan.lts }}.yaml
      - name: Build
        run: |
          stack test --fast --bench --no-run-benchmarks --haddock --no-haddock-deps
        env:
          STACK_YAML: stack${{ matrix.plan.lts }}.yaml
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
